### ISSUE TITLE
Name resolution fails, DNS is missing in wgnet_clientX.conf 

### ISSUE THREAD

**Issue by AlexKay88** [OpenMediaVault-Plugin-Developers/openmediavault-wireguard#11]
DNS name resolution fails for internal hostnames/FQDN via wireguard tunnel.
Option `DNS = <LOCAL_DNS_SERVER>[,<LOCAL_DNS_SERVER>]` is missing in `[Interface]` section of `wgnet_clientX.conf`

Would be great to see a dropdownlist in configuration dialog, which is pre-filled with
a) DNS IP taken from DHCP (if DHCP enabled) or
b) DNS IP taken from static IP configuration and perhaps
c) choice of public available DNS servers, e.g. Google DNS 8.8.8.8

Adding DNS manually to `wgnet_clientX.conf`, as shown below, solves name resolution problem. 

```
[Interface]
Address = xxx
PrivateKey = xxx
DNS = 192.168.2.1

[Peer]
PublicKey = xxx
PresharedKey = xxx
Endpoint = xxx
AllowedIPs = xxx
```

**Comment by AlexKay88** [comment]
Hi @ryecoaaron, I saw you last PR. Would be great, if you could help here as I am not familiar with OMV source code.

**Comment by ryecoaaron** [comment]
While I have written the code, I don't use wireguard.  I'm wondering why all of the people who have helped test haven't needed the DNS line?

**Comment by AlexKay88** [comment]
> While I have written the code, I don't use wireguard. I'm wondering why all of the people who have helped test haven't needed the DNS line?

I don't know how many people are actively using openmediavault-wireguard plugin. But I can say for sure, that a public name server does not know about local network hostnames/FQDN, especially not for private networks such as e.g. 192.168.x.y or 10.x.y.z.
Without asking local DNS one may only connect to IP addresses of local network instead of hostenames/FQDN.

**Comment by ryecoaaron** [comment]
@Dabsunter , would you care to comment?  While this change makes sense, I have no idea what it could cause issues with.

**Comment by ryecoaaron** [comment]
I do understand how DNS works.  I just don't know why other users haven't need the config item.  I guess I could add a DNS text field that if left empty, wouldn't add the DNS entry to the config.  The drop down would be a pain and I don't want to maintain a list of public dns servers.

**Comment by Dabsunter** [comment]
It's true that other tools do propose DNS by default, but it's still an option to left it empty.

In fact it make sense to specify it when client's `AllowedIPs = 0.0.0.0/0` because actually I don't know what is the DNS behaviour if not specified in this scenario...

Personally I haven't encountered the issue because all of my permanents WireGuard connections use a limited `AllowedIPs` in order to route only the necessary traffic so the default DNS config is still in place and work as expected.

For the few times I used a full redirection (`AllowedIPs = 0.0.0.0/0`) I guess the local DNS cache of my computer did his job at hiding me that possible issue...

So maybe there is some investigation to clearly know what is the actual behavior of a setup where `AllowedIPs = 0.0.0.0/0` & `DNS` field undefined... but @AlexKay88 might surely already have ran some tests 😅

**Comment by ryecoaaron** [comment]
I will work on adding it then with the option to leave it blank.

**Comment by Dabsunter** [comment]
If `AllowedIPs = 0.0.0.0/0`, an "always working" default option might be to set `DNS` to the DNS used by the server, but I don't know how easy it is to retrieve that from PHP / saltstack.

If there is the possibility to set our own custom value, there is no need to maintain a huge list of DNS services hardcoded in the plugin 🤔

**Comment by ryecoaaron** [comment]
Getting the dns value isn't too hard but having a dynamic default in the web interface is very hard (not even sure it can be done for new clients).

**Comment by AlexKay88** [comment]
> So maybe there is some investigation to clearly know what is the actual behavior of a setup where `AllowedIPs = 0.0.0.0/0` & `DNS` field undefined... but @AlexKay88 might surely already have ran some tests 😅

Exactly, I did ;-)
If DNS is not specified in `wgnet_clientX.conf` , the client will use it's current system DNS servers.
In my case I tried wireguard client on my mobile phone and it uses the DNS servers of my mobile data provider.
Of course, my mobile data providers DNS can't resolve hostnames on my local network at home.
Furthermore this is a DNS leak, since my mobile data provider can see which domains I request on the internet and at home.
See here: https://github.com/pirate/wireguard-docs#dns

**Comment by ryecoaaron** [comment]
I will try to hurry to get this "fixed" so your mobile data provider can't see your hits to pornhub lol

**Comment by AlexKay88** [comment]
I am sure you already know how to find a list of nameservers with salt. Hope this helps to pre-populate a new DNS field dropdown list along with the option to leave it blank.

```
root@host:/srv/salt/omv# cat testout.sls
{% set grains_dns = salt['grains.get']('dns') %}
test_output:
  file.managed:
    - name: /root/test.out
    - contents: |
        # grains_dns {{ grains_dns }}
        # grains_dns.nameservers {{ grains_dns.nameservers }}

root@host:/srv/salt/omv# cat ~/test.out
# grains_dns {'nameservers': ['192.168.x.1', 'fd88::288:88ff:fe88:1'], 'ip4_nameservers': ['192.168.x.1'], 'ip6_nameservers': ['fd88::288:88ff:fe88:1'], 'sortlist': [], 'domain': '', 'search': ['.'], 'options': []}
# grains_dns.nameservers ['192.168.x.1', 'fd88::288:88ff:fe88:1']
```
